paper:
    latexmk -pvc paper.tex

build:
    latexmk -pvc description.tex

poster:
    latexmk -pvc poster.tex

pdf:
	drawio --export --embed-diagram figs.drawio.svg -g 1..1 -o fig/simple.pdf
	drawio --export --embed-diagram figs.drawio.svg -g 2..2 -o fig/strongly-fixed.pdf
	drawio --export --embed-diagram figs.drawio.svg -g 3..3 -o fig/blocking-set.pdf
	drawio --export --embed-diagram figs.drawio.svg -g 4..4 -o fig/gluing.pdf

export:
    cd .. && zip -r source.zip tex/{paper.tex,bibliography.bib,fig,cc-by.pdf,orcid.pdf,lipics-logo-bw.pdf,lipics-v2021.cls}
