[package]
name = "ocmu64"
version = "0.1.0"
edition = "2021"
default-run = "ocmu64"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
rand = "0.8.5"
